Some structural changes, rework of /pobjects
QBCore-Remastered/qb-policejob pull request #2
Opened 2022-10-07 12:49 UTC by HebiKotei

Changing the structure of server/main.lua, attempting to make it neater. Reworked command /pobjects through the use of a new switch statement. Client triggers added to Config.Objects table through a new function.

This means:
- To add a new object for /pobjects, all you need to do is add a new config line and create a new client event.

**Questions:**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

2022-10-07 14:09 UTC, HebiKotei commented
Found some errors while I was working on adding ox_lib support, have updated the errors out and am continue to add ox_lib.

2022-10-07 14:39 UTC, Manason requested changes

2022-10-07 14:39 UTC, Manason commented on server/main.lua
> +    if not (Player.PlayerData.job.name == "police" and Player.PlayerData.job.grade.level >= Config.LicenseRank) then
```suggestion
    if Player.PlayerData.job.name ~= "police"  or Player.PlayerData.job.grade.level < Config.LicenseRank then
```

A bit easier to read.

2022-10-07 14:39 UTC, Manason commented on server/main.lua
> +    TriggerClientEvent('police:client:SpawnSpikeStrip', src)
I feel this is a less readable change. If I read the left one out loud it is "if player job is police and player is on duty, then spawn a spike strip." The right one is "if the opposite of player job is police and player is on duty, then exit, else spawn a spike strip"

It takes me longer to read the right side.

2022-10-07 14:39 UTC, Manason commented on server/main.lua
> +    if not (args[2] == "driver" or args[2] == "weapon") then
```suggestion
    if args[2] ~= "driver" and args[2] ~= "weapon" then
```

2022-10-07 14:39 UTC, Manason commented on server/main.lua
> +    if not (Player.PlayerData.job.name == "police" and Player.PlayerData.job.grade.level >= Config.LicenseRank) then
```suggestion
    if Player.PlayerData.job.name ~= "police" or Player.PlayerData.job.grade.level < Config.LicenseRank then
```

2022-10-07 14:39 UTC, Manason commented on server/main.lua
> +    if not (args[2] == "driver" or args[2] == "weapon") then
```suggestion
    if args[2] ~= "driver" and args[2] ~= "weapon" then
```

2022-10-07 14:39 UTC, Manason commented on config.lua
> +    end},
I have mixed feelings about this change. On one hand I like that you've encapsulated the spawn function, so that it can be called abstractly in the code. I also like the close association of the object and its associated client event. However, I'm also uncomfortable with Config not being static. Is there another way we could accomplish this? Perhaps instead of a function to trigger the client event in Config itself, we store a string name of the event?

2022-10-07 14:44 UTC, HebiKotei commented on config.lua
> +    end},
Yeah, there is most certainly a way, bare with for the next commit

2022-10-07 14:49 UTC, HebiKotei commented on server/main.lua
> +    if not (Player.PlayerData.job.name == "police" and Player.PlayerData.job.grade.level >= Config.LicenseRank) then
Completely forgot about the ```~=``` operand, will start using afterwards, will commit changes featuring this

2022-10-07 15:00 UTC, HebiKotei commented on server/main.lua
> +    TriggerClientEvent('police:client:SpawnSpikeStrip', src)
I see your poin

2022-10-07 18:10 UTC, Manason approved these changes

2022-10-08 16:06 UTC, D4isDAVID requested changes
Rest of the code seems fine.

2022-10-08 16:06 UTC, D4isDAVID commented on server/main.lua
> +        TriggerClientEvent('ox_lib', src, {description = Lang:t("info.vehicle_flagged", {vehicle = args[1]:upper(), reason = table.concat(reason, " ")})})
```suggestion
        TriggerClientEvent('ox_lib:notify', src, {description = Lang:t("info.vehicle_flagged", {vehicle = args[1]:upper(), reason = table.concat(reason, " ")})})
```
Supposed to be the notify event

2022-10-08 16:34 UTC, HebiKotei commented on server/main.lua
> +        TriggerClientEvent('ox_lib', src, {description = Lang:t("error.have_evidence_bag"), type = "error"})
oops forgot to commit those

2022-10-08 16:37 UTC, D4isDAVID approved these changes

2022-10-08 16:38 UTC, D4isDAVID requested changes

2022-10-08 16:38 UTC, D4isDAVID commented on server/main.lua
> +    TriggerClientEvent('ox_lib', src, {description = Lang:t("info.sent_jail_for", {time = time})})
```suggestion
    TriggerClientEvent('ox_lib:notify', src, {description = Lang:t("info.sent_jail_for", {time = time})})
```
Looks like we missed one more

2022-10-08 16:39 UTC, HebiKotei commented on server/main.lua
> +    TriggerClientEvent('ox_lib', src, {description = Lang:t("info.sent_jail_for", {time = time})})
Right, I'm just gonna push the version I have, because those actually have the changes ;p

2022-10-08 16:43 UTC, D4isDAVID approved these changes

2022-10-08 21:29 UTC, HebiKotei commented
I've requested a re-review, I started looking further into /pobject and reworked it now so that if you wish to add a new police item to spawn, you only need to add a new line into the config.

2022-10-08 22:09 UTC, D4isDAVID requested changes

2022-10-08 22:09 UTC, D4isDAVID commented on client/objects.lua
>              TriggerServerEvent("police:server:deleteObject", objectId)
```suggestion
            TriggerServerEvent("police:server:deleteObject", objectId)
```
Line can be completely removed, ox_lib already stops the animation.

2022-10-08 22:09 UTC, D4isDAVID commented on client/objects.lua
>              StopAnimTask(PlayerPedId(), "weapons@first_person@aim_rng@generic@projectile@thermal_charge@", "plant_floor", 1.0)
Line can be completely removed, ox_lib already stops the animation.

2022-10-08 22:09 UTC, D4isDAVID commented on client/objects.lua
>          StopAnimTask(PlayerPedId(), "anim@narcotics@trash", "drop_front", 1.0)
Line can be completely removed, ox_lib already stops the animation.

2022-10-08 22:09 UTC, D4isDAVID commented on client/objects.lua
>          StopAnimTask(PlayerPedId(), "anim@narcotics@trash", "drop_front", 1.0)
Line can be completely removed, ox_lib already stops the animation.

2022-10-08 22:09 UTC, D4isDAVID commented on client/objects.lua
> +        lib.cancel()
Probably supposed to be `lib.cancelProgress()`, but this isn't even needed, since this code is executed after the progress is *already* cancelled.

2022-10-08 22:18 UTC, HebiKotei commented on client/objects.lua
> +        lib.cancel()
That was a leftover from The standard qb-policejob implementation. left in by acciden

2022-10-08 22:50 UTC, D4isDAVID approved these changes
Very nice improvement.

2022-10-09 13:43 UTC, HebiKotei commented
@ChatDisabled <3 pls

2022-10-10 02:22 UTC, Manason approved these changes

2022-10-10 02:22 UTC, Manason commented on client/objects.lua
> +RegisterNetEvent('police:client:spawnPObj', function(item)
Add function header. See https://github.com/sumneko/lua-language-server/wiki/Annotations

2022-10-10 02:22 UTC, Manason commented on client/objects.lua
>          QBCore.Functions.Notify(Lang:t("error.no_spikestripe"), 'error')
Why is this a QBCore notify, but the above is a ox lib notify?

2022-10-10 02:22 UTC, Manason commented on client/objects.lua
>  RegisterNetEvent('police:client:SpawnSpikeStrip', function()
function header would be appreciated here https://github.com/sumneko/lua-language-server/wiki/Annotations

2022-10-10 04:47 UTC, D4isDAVID commented on client/objects.lua
>          QBCore.Functions.Notify(Lang:t("error.no_spikestripe"), 'error')
This should be ox_lib, I didn't catch this when requesting changes previously.

2022-10-10 04:54 UTC, D4isDAVID commented on client/objects.lua
>          QBCore.Functions.Notify(Lang:t("error.no_spikestripe"), 'error')
Resolving this to request changes properly.

2022-10-10 04:55 UTC, D4isDAVID requested changes

2022-10-10 04:55 UTC, D4isDAVID commented on client/objects.lua
>          QBCore.Functions.Notify(Lang:t("error.no_spikestripe"), 'error')
```suggestion
        lib.notify({ description = Lang:t("error.no_spikestripe"), type = 'error' })
```
Change to ox_lib notification.

2022-10-10 04:59 UTC, Manason commented on client/objects.lua
>          QBCore.Functions.Notify(Lang:t("error.no_spikestripe"), 'error')
Consider combining these two ifs with an or condition as the body of both are the same

2022-10-10 05:00 UTC, D4isDAVID commented on client/objects.lua
>          QBCore.Functions.Notify(Lang:t("error.no_spikestripe"), 'error')
True that, didn't notice

2022-10-10 05:01 UTC, D4isDAVID requested changes

2022-10-10 05:01 UTC, D4isDAVID commented on client/objects.lua
>      end
```suggestion
    if #SpawnedSpikes >= Config.MaxSpikes or PlayerJob.name ~= "police" or not PlayerJob.onduty then
        lib.notify({ description = Lang:t("error.no_spikestripe"), type = 'error'})
        return
    end
```
Combine these

2022-10-10 12:34 UTC, HebiKotei commented
@Manason Your changes have been addressed, please lmk if they are fine as is or if they need to be changed in any way.
@D4isDAVID You suggested changes have been addressed.

Linter is not recognising ```lib``` from ox_lib, which is why the checks are failing in CI.

2022-10-10 14:44 UTC, D4isDAVID requested changes
Seems fine, my only other concern is that qb-radialmenu can't place objects after these changes.

2022-10-10 14:57 UTC, HebiKotei commented
> Seems fine, my only other concern is that qb-radialmenu can't place objects after these changes.

I'll take a look at qb-radial menu

2022-10-10 14:58 UTC, D4isDAVID approved these changes

2022-10-10 15:12 UTC, Manason approved these changes

2022-10-12 13:20 UTC, merged